name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose

  test-cross:
    name: Test ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: aarch64-unknown-linux-gnu
            cross-version: 0.2.5
          - target: armv7-unknown-linux-gnueabihf
            cross-version: 0.2.5

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Install cross
        run: cargo install cross --git https://github.com/cross-rs/cross

      - name: Build
        run: cross build --verbose --target ${{ matrix.target }}

      - name: Run tests
        run: cross test --verbose --target ${{ matrix.target }}
